-- Navigation items for the admin area
-- Depends on: local_text_link entries generated by sveltebuilder sync:supabase

insert into public.navigation_item (local_text_link_id, href, scope, sort_order)
select l.id, nav.href, nav.scope, nav.sort_order
from (values
  ('admin.nav.dashboard',      '/admin/dashboard',       'admin', 10),
  ('admin.nav.local_text',     '/admin/local-text',      'admin', 20),
  ('admin.nav.locale',         '/admin/locale',          'admin', 30),
  ('admin.nav.navigation_item','/admin/navigation-item', 'admin', 40)
) as nav(slug, href, scope, sort_order)
join public.local_text_link l
  on l.slug = nav.slug and l.scope is null and l.entity_id is null
on conflict (href, scope) do nothing;
