-- Navigation items for the admin area
-- Depends on: local_text_link entries generated by sveltebuilder sync:supabase
--
-- The settings items sort after every newsroom item (100+) because the admin layout
-- pulls them into the collapsible "Application settings" group, and the newsroom
-- links stay top level. Which hrefs belong to the group, and each item's icon, is
-- decided in src/routes/(admin)/admin-navigation.ts.

insert into public.navigation_item (local_text_link_id, href, scope, sort_order)
select l.id, nav.href, nav.scope, nav.sort_order
from (values
  ('admin.nav.dashboard',      '/admin/dashboard',       'admin', 10),
  ('admin.nav.local_text',     '/admin/local-text',      'admin', 120),
  ('admin.nav.locale',         '/admin/locale',          'admin', 130),
  ('admin.nav.navigation_item','/admin/navigation-item', 'admin', 140)
) as nav(slug, href, scope, sort_order)
join public.local_text_link l
  on l.slug = nav.slug and l.scope is null and l.entity_id is null
on conflict (href, scope) do nothing;

-- ── Newspaper wording for the base nav labels ─────────────────────────────────
-- The generated base seed above this file ships generic labels ("Content",
-- "Locales") with `do nothing`, and it is regenerated on every sync, so the
-- newsroom wording is applied here as an override instead of edited there.
-- "Translations" rather than "Content": in a newspaper, content means stories.
insert into public.local_text_link (slug, scope, entity_id)
values ('admin.nav.application_settings', null, null)
on conflict do nothing;

insert into public.local_text (link, locale, content)
select l.id, (select id from public.locale where code = v.code), v.content
from (values
  ('admin.nav.dashboard',            'en', 'Overview'),
  ('admin.nav.dashboard',            'fr', 'Vue d''ensemble'),
  ('admin.nav.local_text',           'en', 'Translations'),
  ('admin.nav.local_text',           'fr', 'Traductions'),
  ('admin.nav.locale',               'en', 'Languages'),
  ('admin.nav.locale',               'fr', 'Langues'),
  ('admin.nav.navigation_item',      'en', 'Menus'),
  ('admin.nav.navigation_item',      'fr', 'Menus'),
  ('admin.nav.application_settings', 'en', 'Application settings'),
  ('admin.nav.application_settings', 'fr', 'Paramètres de l''application')
) as v(slug, code, content)
join public.local_text_link l on l.slug = v.slug and l.scope is null and l.entity_id is null
on conflict (link, locale) do update set content = excluded.content;
