-- Content module supplements: updated_at triggers, cross-package FKs.
--
-- RLS predicates use public.current_user_id() (bigint) and user_account.admin.
-- Never use auth.uid(), auth.jwt(), or uuid comparisons here.
--
-- Drizzle-kit generates CREATE TABLE for all content tables. This file adds:
--   1. set_updated_at() trigger function (not generated by Drizzle)
--   2. Triggers on article and comment for auto-updating updated_at
--   3. Cross-package FKs to user_account (cannot be expressed in the module schema)

-- ── updated_at trigger function ───────────────────────────────────────────────
--
-- Both this module and @sveltebuilder/logistic define public.set_updated_at(), and
-- `create or replace` on the same signature means whichever supplemental file is appended
-- last wins. The two definitions must therefore stay identical, or installing both modules
-- would silently change which one a project gets: logistic sorts after content, so its
-- version is the one that survives today. Keeping them the same removes the question.
--
-- `set search_path = ''` because now() resolves from pg_catalog, which is always in scope,
-- so pinning it costs nothing and stops the trigger being redirected through a shadowed
-- object.
create or replace function public.set_updated_at()
returns trigger language plpgsql
set search_path = ''
as $$
begin new.updated_at = now(); return new; end; $$;

create or replace trigger article_set_updated_at
  before update on public.article
  for each row execute function public.set_updated_at();

create or replace trigger comment_set_updated_at
  before update on public.comment
  for each row execute function public.set_updated_at();

-- ── Cross-package foreign keys ────────────────────────────────────────────────
-- Wrapped in DO blocks so re-running sync:supabase doesn't fail on duplicate constraints.

do $$ begin
  alter table public.article_assignment
    add constraint fk_article_assignment_user_account
    foreign key (user_account_id) references public.user_account(id) on delete cascade;
exception when duplicate_object then null;
end $$;

do $$ begin
  alter table public.article_revision
    add constraint fk_article_revision_user_account
    foreign key (user_account_id) references public.user_account(id) on delete cascade;
exception when duplicate_object then null;
end $$;

do $$ begin
  alter table public.author_profile
    add constraint fk_author_profile_user_account
    foreign key (user_account_id) references public.user_account(id) on delete set null;
exception when duplicate_object then null;
end $$;

do $$ begin
  alter table public.comment
    add constraint fk_comment_user_account
    foreign key (user_account_id) references public.user_account(id) on delete set null;
exception when duplicate_object then null;
end $$;

do $$ begin
  alter table public.media_asset
    add constraint fk_media_asset_uploaded_by
    foreign key (uploaded_by) references public.user_account(id) on delete restrict;
exception when duplicate_object then null;
end $$;
