CREATE TYPE "public"."article_assignment_role" AS ENUM('author', 'editor', 'photo', 'copy');--> statement-breakpoint
CREATE TYPE "public"."article_block_type" AS ENUM('paragraph', 'heading', 'image', 'gallery', 'video', 'embed', 'pullquote', 'live_update');--> statement-breakpoint
CREATE TYPE "public"."comment_status" AS ENUM('pending', 'approved', 'rejected', 'flagged');--> statement-breakpoint
CREATE TYPE "public"."front_layout_variant" AS ENUM('lead', 'secondary', 'river', 'brief');--> statement-breakpoint
CREATE TYPE "public"."media_license" AS ENUM('all_rights_reserved', 'rights_managed', 'royalty_free', 'creative_commons', 'public_domain');--> statement-breakpoint
CREATE TYPE "public"."media_type" AS ENUM('image', 'video', 'audio', 'document');--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "local_text" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "local_text_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"link" bigint NOT NULL,
	"locale" bigint NOT NULL,
	"content" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "local_text_link" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "local_text_link_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"scope" text,
	"entity_id" bigint,
	CONSTRAINT "uq_local_text_link_slug_scope_entity" UNIQUE NULLS NOT DISTINCT("slug","scope","entity_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "locale" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "locale_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"code" text NOT NULL,
	"name" text NOT NULL,
	"native_name" text NOT NULL,
	"dir" text DEFAULT 'ltr' NOT NULL,
	CONSTRAINT "locale_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "navigation_item" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "navigation_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"local_text_link_id" bigint NOT NULL,
	"href" text NOT NULL,
	"scope" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "user_account" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "user_account_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"auth_user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"active" boolean DEFAULT true NOT NULL,
	"admin" boolean DEFAULT false NOT NULL,
	CONSTRAINT "user_account_auth_user_id_unique" UNIQUE("auth_user_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "article" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "article_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"article_status_id" bigint NOT NULL,
	"canonical_slug" text NOT NULL,
	"published_at" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"embargo_until" timestamp with time zone,
	"allow_comment" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "article_canonical_slug_unique" UNIQUE("canonical_slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "article_assignment" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "article_assignment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"article_id" bigint NOT NULL,
	"user_account_id" bigint NOT NULL,
	"role" "article_assignment_role" NOT NULL,
	"assigned_at" timestamp with time zone DEFAULT now() NOT NULL,
	"due_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "article_block" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "article_block_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"article_id" bigint NOT NULL,
	"block_type" "article_block_type" NOT NULL,
	"position" integer NOT NULL,
	"content" jsonb DEFAULT '{}' NOT NULL,
	"media_asset_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "article_byline" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "article_byline_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"article_id" bigint NOT NULL,
	"author_profile_id" bigint NOT NULL,
	"position" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "article_checklist_state" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "article_checklist_state_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"article_id" bigint NOT NULL,
	"publish_checklist_item_id" bigint NOT NULL,
	"satisfied" boolean DEFAULT false NOT NULL,
	"satisfied_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "article_preview_token" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "article_preview_token_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"article_id" bigint NOT NULL,
	"token" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "article_preview_token_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "article_revision" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "article_revision_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"article_id" bigint NOT NULL,
	"user_account_id" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "article_section" (
	"article_id" bigint NOT NULL,
	"section_id" bigint NOT NULL,
	CONSTRAINT "article_section_article_id_section_id_pk" PRIMARY KEY("article_id","section_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "article_status" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "article_status_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"ordinal" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "article_status_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "article_tag" (
	"article_id" bigint NOT NULL,
	"tag_id" bigint NOT NULL,
	CONSTRAINT "article_tag_article_id_tag_id_pk" PRIMARY KEY("article_id","tag_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "article_topic" (
	"article_id" bigint NOT NULL,
	"topic_id" bigint NOT NULL,
	CONSTRAINT "article_topic_article_id_topic_id_pk" PRIMARY KEY("article_id","topic_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "author_profile" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "author_profile_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_account_id" bigint,
	"slug" text NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "author_profile_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "comment" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "comment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"article_id" bigint NOT NULL,
	"user_account_id" bigint,
	"parent_comment_id" bigint,
	"author_name" text NOT NULL,
	"author_email" text NOT NULL,
	"body" text NOT NULL,
	"status" "comment_status" DEFAULT 'pending' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "front" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "front_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"section_id" bigint,
	"slug" text NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "front_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "front_slot" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "front_slot_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"front_id" bigint NOT NULL,
	"article_id" bigint NOT NULL,
	"position" integer NOT NULL,
	"layout_variant" "front_layout_variant" DEFAULT 'river' NOT NULL,
	"pinned_until" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "live_coverage" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "live_coverage_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"article_id" bigint NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ended_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "live_update" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "live_update_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"live_coverage_id" bigint NOT NULL,
	"published_at" timestamp with time zone DEFAULT now() NOT NULL,
	"pinned" boolean DEFAULT false NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "media_asset" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "media_asset_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"media_type" "media_type" NOT NULL,
	"storage_key" text NOT NULL,
	"width" integer,
	"height" integer,
	"mime_type" text NOT NULL,
	"uploaded_by" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "media_asset_storage_key_unique" UNIQUE("storage_key")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "media_asset_rights" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "media_asset_rights_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"media_asset_id" bigint NOT NULL,
	"license" "media_license" DEFAULT 'all_rights_reserved' NOT NULL,
	"credit_required" boolean DEFAULT true NOT NULL,
	"expires_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "newsletter" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "newsletter_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "newsletter_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "newsletter_subscription" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "newsletter_subscription_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"newsletter_id" bigint NOT NULL,
	"subscriber_id" bigint NOT NULL,
	"subscribed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"unsubscribed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "publish_checklist_item" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "publish_checklist_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"ordinal" integer DEFAULT 0 NOT NULL,
	"required" boolean DEFAULT true NOT NULL,
	CONSTRAINT "publish_checklist_item_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "publisher_profile" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "publisher_profile_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"logo_media_asset_id" bigint,
	"url" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "section" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "section_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"parent_section_id" bigint,
	"slug" text NOT NULL,
	"ordinal" integer DEFAULT 0 NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "section_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "subscriber" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "subscriber_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"email_address" text NOT NULL,
	"locale" text DEFAULT 'en' NOT NULL,
	"confirmed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "subscriber_email_address_unique" UNIQUE("email_address")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "tag" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "tag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tag_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "topic" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "topic_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "topic_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "local_text" ADD CONSTRAINT "local_text_link_local_text_link_id_fk" FOREIGN KEY ("link") REFERENCES "public"."local_text_link"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "local_text" ADD CONSTRAINT "local_text_locale_locale_id_fk" FOREIGN KEY ("locale") REFERENCES "public"."locale"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "navigation_item" ADD CONSTRAINT "navigation_item_local_text_link_id_local_text_link_id_fk" FOREIGN KEY ("local_text_link_id") REFERENCES "public"."local_text_link"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "user_account" ADD CONSTRAINT "user_account_auth_user_id_users_id_fk" FOREIGN KEY ("auth_user_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "article" ADD CONSTRAINT "article_article_status_id_article_status_id_fk" FOREIGN KEY ("article_status_id") REFERENCES "public"."article_status"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "article_assignment" ADD CONSTRAINT "article_assignment_article_id_article_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."article"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "article_block" ADD CONSTRAINT "article_block_article_id_article_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."article"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "article_block" ADD CONSTRAINT "article_block_media_asset_id_media_asset_id_fk" FOREIGN KEY ("media_asset_id") REFERENCES "public"."media_asset"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "article_byline" ADD CONSTRAINT "article_byline_article_id_article_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."article"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "article_byline" ADD CONSTRAINT "article_byline_author_profile_id_author_profile_id_fk" FOREIGN KEY ("author_profile_id") REFERENCES "public"."author_profile"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "article_checklist_state" ADD CONSTRAINT "article_checklist_state_article_id_article_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."article"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "article_checklist_state" ADD CONSTRAINT "article_checklist_state_publish_checklist_item_id_publish_checklist_item_id_fk" FOREIGN KEY ("publish_checklist_item_id") REFERENCES "public"."publish_checklist_item"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "article_preview_token" ADD CONSTRAINT "article_preview_token_article_id_article_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."article"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "article_revision" ADD CONSTRAINT "article_revision_article_id_article_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."article"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "article_section" ADD CONSTRAINT "article_section_article_id_article_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."article"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "article_section" ADD CONSTRAINT "article_section_section_id_section_id_fk" FOREIGN KEY ("section_id") REFERENCES "public"."section"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "article_tag" ADD CONSTRAINT "article_tag_article_id_article_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."article"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "article_tag" ADD CONSTRAINT "article_tag_tag_id_tag_id_fk" FOREIGN KEY ("tag_id") REFERENCES "public"."tag"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "article_topic" ADD CONSTRAINT "article_topic_article_id_article_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."article"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "article_topic" ADD CONSTRAINT "article_topic_topic_id_topic_id_fk" FOREIGN KEY ("topic_id") REFERENCES "public"."topic"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "comment" ADD CONSTRAINT "comment_article_id_article_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."article"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "comment" ADD CONSTRAINT "comment_parent_comment_id_comment_id_fk" FOREIGN KEY ("parent_comment_id") REFERENCES "public"."comment"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "front" ADD CONSTRAINT "front_section_id_section_id_fk" FOREIGN KEY ("section_id") REFERENCES "public"."section"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "front_slot" ADD CONSTRAINT "front_slot_front_id_front_id_fk" FOREIGN KEY ("front_id") REFERENCES "public"."front"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "front_slot" ADD CONSTRAINT "front_slot_article_id_article_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."article"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "live_coverage" ADD CONSTRAINT "live_coverage_article_id_article_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."article"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "live_update" ADD CONSTRAINT "live_update_live_coverage_id_live_coverage_id_fk" FOREIGN KEY ("live_coverage_id") REFERENCES "public"."live_coverage"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "media_asset_rights" ADD CONSTRAINT "media_asset_rights_media_asset_id_media_asset_id_fk" FOREIGN KEY ("media_asset_id") REFERENCES "public"."media_asset"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "newsletter_subscription" ADD CONSTRAINT "newsletter_subscription_newsletter_id_newsletter_id_fk" FOREIGN KEY ("newsletter_id") REFERENCES "public"."newsletter"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "newsletter_subscription" ADD CONSTRAINT "newsletter_subscription_subscriber_id_subscriber_id_fk" FOREIGN KEY ("subscriber_id") REFERENCES "public"."subscriber"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "publisher_profile" ADD CONSTRAINT "publisher_profile_logo_media_asset_id_media_asset_id_fk" FOREIGN KEY ("logo_media_asset_id") REFERENCES "public"."media_asset"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "section" ADD CONSTRAINT "section_parent_section_id_section_id_fk" FOREIGN KEY ("parent_section_id") REFERENCES "public"."section"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_local_text_entry" ON "local_text" USING btree ("link","locale");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_navigation_item_href_scope" ON "navigation_item" USING btree ("href","scope");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_user_account_auth_user_id" ON "user_account" USING btree ("auth_user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_article_status" ON "article" USING btree ("article_status_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_article_canonical_slug" ON "article" USING btree ("canonical_slug");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_article_embargo" ON "article" USING btree ("embargo_until");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_article_assignment" ON "article_assignment" USING btree ("article_id","user_account_id","role");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_article_assignment_article" ON "article_assignment" USING btree ("article_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_article_assignment_user" ON "article_assignment" USING btree ("user_account_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_article_block_article" ON "article_block" USING btree ("article_id","position");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_article_block_media" ON "article_block" USING btree ("media_asset_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_article_byline" ON "article_byline" USING btree ("article_id","author_profile_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_article_byline_article" ON "article_byline" USING btree ("article_id","position");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_article_byline_author" ON "article_byline" USING btree ("author_profile_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_article_checklist_state" ON "article_checklist_state" USING btree ("article_id","publish_checklist_item_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_article_checklist_state_article" ON "article_checklist_state" USING btree ("article_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_article_preview_token_article" ON "article_preview_token" USING btree ("article_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_article_preview_token_token" ON "article_preview_token" USING btree ("token");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_article_preview_token_expiry" ON "article_preview_token" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_article_revision_article" ON "article_revision" USING btree ("article_id","created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_article_section_section" ON "article_section" USING btree ("section_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_article_status_ordinal" ON "article_status" USING btree ("ordinal");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_article_tag_tag" ON "article_tag" USING btree ("tag_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_article_topic_topic" ON "article_topic" USING btree ("topic_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_author_profile_user" ON "author_profile" USING btree ("user_account_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_author_profile_slug" ON "author_profile" USING btree ("slug");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_comment_article" ON "comment" USING btree ("article_id","created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_comment_parent" ON "comment" USING btree ("parent_comment_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_comment_status" ON "comment" USING btree ("article_id","status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_comment_user" ON "comment" USING btree ("user_account_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_front_section_id" ON "front" USING btree ("section_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_front_section" ON "front" USING btree ("section_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_front_slot_front" ON "front_slot" USING btree ("front_id","position");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_front_slot_article" ON "front_slot" USING btree ("article_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_front_slot_pinned" ON "front_slot" USING btree ("pinned_until");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_live_coverage_article" ON "live_coverage" USING btree ("article_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_live_coverage_article" ON "live_coverage" USING btree ("article_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_live_coverage_active" ON "live_coverage" USING btree ("active");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_live_update_coverage" ON "live_update" USING btree ("live_coverage_id","position");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_live_update_published" ON "live_update" USING btree ("published_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_live_update_pinned" ON "live_update" USING btree ("live_coverage_id","pinned");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_media_asset_uploader" ON "media_asset" USING btree ("uploaded_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_media_asset_type" ON "media_asset" USING btree ("media_type");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_media_asset_rights_asset" ON "media_asset_rights" USING btree ("media_asset_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_newsletter_subscription" ON "newsletter_subscription" USING btree ("newsletter_id","subscriber_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_newsletter_subscription_newsletter" ON "newsletter_subscription" USING btree ("newsletter_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_newsletter_subscription_subscriber" ON "newsletter_subscription" USING btree ("subscriber_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_publish_checklist_item_ordinal" ON "publish_checklist_item" USING btree ("ordinal");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_publisher_profile_logo" ON "publisher_profile" USING btree ("logo_media_asset_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_section_parent" ON "section" USING btree ("parent_section_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_section_ordinal" ON "section" USING btree ("ordinal");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_subscriber_email" ON "subscriber" USING btree ("email_address");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_subscriber_confirmed" ON "subscriber" USING btree ("confirmed_at");
-- supplemental: 00-auth-functions.sql
-- Auth helper functions
--
-- These three functions are the whole bridge between Supabase Auth's identity
-- (auth.users.id, a uuid, reachable in SQL as auth.uid()) and the domain
-- principal (public.user_account.id, a bigint). Every RLS policy in this project
-- goes through current_user_id() or current_user_admin(); no policy references
-- auth.uid() directly, so the mapping lives in exactly one place and swapping
-- identity providers means rewriting these bodies and nothing else.
--
-- This file must sort FIRST among supplemental files (00- prefix): the RLS files
-- that follow call these functions.
--
-- WHY SECURITY DEFINER: each function reads public.user_account, which is itself
-- RLS-protected. As SECURITY INVOKER they would re-enter user_account's own
-- policies — and user_account's admin policy calls current_user_admin(), so a
-- policy would be consulting a function that reads the table the policy is on.
-- Postgres raises "infinite recursion detected in policy for relation" on that.
-- SECURITY DEFINER reads the table without RLS and breaks the cycle; this is the
-- pattern Supabase documents for exactly this case.
--
-- WHY STABLE on the two read-only functions: Postgres evaluates STABLE functions
-- once per statement rather than once per row. Called as
-- (select public.current_user_id()) from a policy, the planner hoists them into
-- an InitPlan evaluated a single time per statement. VOLATILE re-runs per row.
--
-- WHY set search_path = '': a SECURITY DEFINER function otherwise inherits the
-- caller's search_path, letting a caller shadow an unqualified name with their own
-- object and have it execute with the definer's privileges. Every reference below
-- is fully schema-qualified for the same reason.
--
-- Note: there is no `create schema auth` here. On Supabase the auth schema is
-- created and owned by the platform.

-- ── Identity → domain principal ───────────────────────────────────────────────

create or replace function public.current_user_id()
returns bigint
language sql
stable
security definer
set search_path = ''
as $$
  select ua.id
  from public.user_account ua
  where ua.auth_user_id = (select auth.uid())
$$;

create or replace function public.current_user_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (
      select ua.admin
      from public.user_account ua
      where ua.auth_user_id = (select auth.uid())
    ),
    false
  )
$$;

-- ── Just-in-time provisioning ─────────────────────────────────────────────────
--
-- Creates the domain principal on first sign-in and returns its id.
--
-- The identity comes from auth.uid(), never a parameter: a caller cannot
-- provision or claim a row for somebody else's auth identity.
--
-- The first user_account row ever created is granted admin, because a freshly
-- seeded database has no other route into the admin area. That emptiness check
-- MUST run as definer. Under RLS a brand-new user can see no user_account rows at
-- all, so the same test written in application code reads "table is empty" for
-- every new user and hands admin to everybody. Promote or revoke admins with a
-- direct SQL update after the first one; there is no invite UI.

create or replace function public.ensure_user_account()
returns bigint
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_auth_user_id uuid := (select auth.uid());
  v_id bigint;
begin
  if v_auth_user_id is null then
    return null;
  end if;

  select ua.id into v_id
  from public.user_account ua
  where ua.auth_user_id = v_auth_user_id;

  if v_id is not null then
    return v_id;
  end if;

  insert into public.user_account (auth_user_id, admin)
  values (v_auth_user_id, not exists (select 1 from public.user_account))
  on conflict (auth_user_id) do nothing
  returning id into v_id;

  if v_id is null then
    -- Lost the race with a concurrent request provisioning the same identity.
    select ua.id into v_id
    from public.user_account ua
    where ua.auth_user_id = v_auth_user_id;
  end if;

  return v_id;
end;
$$;

-- ── Grants ────────────────────────────────────────────────────────────────────
--
-- anon can call the two read-only helpers (both return null/false with no
-- session, which is what the policies want). ensure_user_account writes, so it is
-- authenticated-only.

grant execute on function public.current_user_id() to authenticated, anon;
grant execute on function public.current_user_admin() to authenticated, anon;
grant execute on function public.ensure_user_account() to authenticated;


-- supplemental: 00-local-text-rls.sql
-- RLS policies for the i18n tables: locale, local_text_link, local_text
--
-- All three are public-read: the dictionary has to resolve for anonymous visitors
-- on server-rendered pages. Writes are admin-only.
--
-- Admin access is gated on user_account.admin via public.current_user_admin(),
-- not on an identity-provider role claim — which is what keeps this file
-- provider-neutral. The scaffold template supplies that function (SuperPrototype:
-- supabase/supplemental/00-auth-functions.sql, which resolves it from auth.uid()).
-- Any other template has to define public.current_user_admin() and
-- public.current_user_id() with the same signatures before this file runs.
--
-- Helpers are called as (select public.current_user_admin()) so the planner
-- evaluates the STABLE function once per statement rather than once per row, and
-- every policy names its role with `to`. Both are standard Postgres/Supabase RLS
-- practice.

alter table public.locale enable row level security;

drop policy if exists "locale_public_read" on public.locale;
create policy "locale_public_read"
  on public.locale for select
  to anon, authenticated
  using (true);

drop policy if exists "locale_admin_write" on public.locale;
create policy "locale_admin_write"
  on public.locale for all
  to authenticated
  using ((select public.current_user_admin()))
  with check ((select public.current_user_admin()));

-- ────────────────────────────────────────────────────────────────────────────

alter table public.local_text_link enable row level security;

drop policy if exists "local_text_link_public_read" on public.local_text_link;
create policy "local_text_link_public_read"
  on public.local_text_link for select
  to anon, authenticated
  using (true);

drop policy if exists "local_text_link_admin_write" on public.local_text_link;
create policy "local_text_link_admin_write"
  on public.local_text_link for all
  to authenticated
  using ((select public.current_user_admin()))
  with check ((select public.current_user_admin()));

-- ────────────────────────────────────────────────────────────────────────────

alter table public.local_text enable row level security;

drop policy if exists "local_text_public_read" on public.local_text;
create policy "local_text_public_read"
  on public.local_text for select
  to anon, authenticated
  using (true);

drop policy if exists "local_text_admin_write" on public.local_text;
create policy "local_text_admin_write"
  on public.local_text for all
  to authenticated
  using ((select public.current_user_admin()))
  with check ((select public.current_user_admin()));


-- supplemental: 01-content-supplements.sql
-- Content module supplements: updated_at triggers, cross-package FKs.
--
-- RLS predicates use public.current_user_id() (bigint) and user_account.admin.
-- Never use auth.uid(), auth.jwt(), or uuid comparisons here.
--
-- Drizzle-kit generates CREATE TABLE for all content tables. This file adds:
--   1. set_updated_at() trigger function (not generated by Drizzle)
--   2. Triggers on article and comment for auto-updating updated_at
--   3. Cross-package FKs to user_account (cannot be expressed in the module schema)

-- ── updated_at trigger function ───────────────────────────────────────────────
--
-- Both this module and @sveltebuilder/logistic define public.set_updated_at(), and
-- `create or replace` on the same signature means whichever supplemental file is appended
-- last wins. The two definitions must therefore stay identical, or installing both modules
-- would silently change which one a project gets: logistic sorts after content, so its
-- version is the one that survives today. Keeping them the same removes the question.
--
-- `set search_path = ''` because now() resolves from pg_catalog, which is always in scope,
-- so pinning it costs nothing and stops the trigger being redirected through a shadowed
-- object.
create or replace function public.set_updated_at()
returns trigger language plpgsql
set search_path = ''
as $$
begin new.updated_at = now(); return new; end; $$;

create or replace trigger article_set_updated_at
  before update on public.article
  for each row execute function public.set_updated_at();

create or replace trigger comment_set_updated_at
  before update on public.comment
  for each row execute function public.set_updated_at();

-- ── Cross-package foreign keys ────────────────────────────────────────────────
-- Wrapped in DO blocks so re-running sync:supabase doesn't fail on duplicate constraints.

do $$ begin
  alter table public.article_assignment
    add constraint fk_article_assignment_user_account
    foreign key (user_account_id) references public.user_account(id) on delete cascade;
exception when duplicate_object then null;
end $$;

do $$ begin
  alter table public.article_revision
    add constraint fk_article_revision_user_account
    foreign key (user_account_id) references public.user_account(id) on delete cascade;
exception when duplicate_object then null;
end $$;

do $$ begin
  alter table public.author_profile
    add constraint fk_author_profile_user_account
    foreign key (user_account_id) references public.user_account(id) on delete set null;
exception when duplicate_object then null;
end $$;

do $$ begin
  alter table public.comment
    add constraint fk_comment_user_account
    foreign key (user_account_id) references public.user_account(id) on delete set null;
exception when duplicate_object then null;
end $$;

do $$ begin
  alter table public.media_asset
    add constraint fk_media_asset_uploaded_by
    foreign key (uploaded_by) references public.user_account(id) on delete restrict;
exception when duplicate_object then null;
end $$;


-- supplemental: 01-get-dictionary.sql
-- PostgreSQL function: get_dictionary
--
-- Fetches the resolved i18n dictionary for a locale (with fallback) in a
-- single query. This is the only place locale-priority resolution happens —
-- diglossia's createDictionary() trusts its payload to already carry one row
-- per key, and the root layout server load calls this function to build
-- that payload.
--
-- security invoker, not security definer: all three tables already carry
-- public-read RLS (see 00-local-text-rls.sql), so definer would bypass RLS
-- for no benefit and open a privilege-escalation surface. If a future
-- requirement forces security definer, it must carry
-- `set search_path = ''` with every reference fully schema-qualified.

create or replace function public.get_dictionary(
  user_locale_code     text,
  fallback_locale_code text,
  scope_filter         text default null,
  entity_id_filter     bigint default null
)
returns table (
  link_id     bigint,
  slug        text,
  scope       text,
  entity_id   bigint,
  content     text,
  locale_code text
)
language sql
stable
security invoker
as $$
  select distinct on (ltl.slug, ltl.scope, ltl.entity_id)
    ltl.id        as link_id,
    ltl.slug,
    ltl.scope,
    ltl.entity_id,
    lt.content,
    l.code        as locale_code
  from public.local_text lt
  join public.local_text_link ltl on ltl.id = lt.link
  join public.locale l on l.id = lt.locale
  where l.code in (user_locale_code, fallback_locale_code)
    and (
      (scope_filter is null and ltl.scope is null)
      or ltl.scope = scope_filter
    )
    and (
      (entity_id_filter is null and ltl.entity_id is null)
      or ltl.entity_id = entity_id_filter
    )
  order by
    ltl.slug,
    ltl.scope,
    ltl.entity_id,
    case when l.code = user_locale_code then 0 else 1 end
$$;


-- supplemental: 02-content-rls.sql
-- Content module RLS
--
-- Every table this module creates had row level security DISABLED until now, which with
-- Supabase's bootstrap grants (all privileges on public tables to anon and authenticated)
-- meant anyone holding the publishable key could read and write all 27 of them —
-- `subscriber` and `comment` included. Verified exploitable before writing this file: as
-- the anon role, inserting and then deleting every row of `subscriber` both succeeded.
--
-- Conventions, matching superprototype's 03-base-rls.sql:
--   1. Helpers are called as `(select public.current_user_admin())`, never bare, so the
--      planner hoists them into an InitPlan evaluated once per statement.
--   2. Every policy names its roles with `to`, so a policy cannot silently apply to a role
--      nobody considered.
--   3. Admin gating goes through public.current_user_admin() rather than an inline
--      `exists (select 1 from public.user_account …)`, which would run as the caller and so
--      depend on user_account's own read policy staying as it is.
--
-- The access model in one paragraph: published editorial content is world-readable;
-- editorial workflow (revisions, assignments, checklists), media licensing terms, preview
-- tokens and subscriber PII are admin-only; comments are world-readable once approved and
-- world-insertable as pending; and newsletter signup goes through a SECURITY DEFINER
-- function rather than granting anon any access to `subscriber` at all.

-- ── Visibility helper ─────────────────────────────────────────────────────────
--
-- The public-visibility rule for an article, in one place: not soft-deleted, status
-- 'published', and past any embargo. It is the same predicate the module's own queries
-- used, so a row the application considered public is exactly a row RLS now admits.
--
-- SECURITY DEFINER is load-bearing twice over. It keeps the function from re-entering
-- `article`'s own policy — which would be infinite recursion for the policy that calls it —
-- and it lets a dependent table (a block, a byline) ask about an article the caller may not
-- otherwise read. STABLE and `set search_path = ''` for the usual reasons.
create or replace function public.content_article_public(p_article_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.article a
    join public.article_status s on s.id = a.article_status_id
    where a.id = p_article_id
      and a.deleted_at is null
      and s.slug = 'published'
      and (a.embargo_until is null or a.embargo_until <= now())
  )
$$;

grant execute on function public.content_article_public(bigint) to anon, authenticated;

-- ── Public taxonomy and chrome ────────────────────────────────────────────────
--
-- Read by anyone, written by admins. None of these carry anything that is not already on
-- the page: a section's name, a tag, the publisher's own profile. article_status is in this
-- group because every public query resolves the slug 'published' through it — with it
-- unreadable, the site shows nothing at all.

do $$
declare
  v_table text;
begin
  foreach v_table in array array[
    'article_status', 'section', 'topic', 'tag', 'author_profile', 'publisher_profile',
    'media_asset', 'newsletter', 'front', 'front_slot'
  ] loop
    execute format('alter table public.%I enable row level security', v_table);

    execute format('drop policy if exists %I on public.%I',
      'content_' || v_table || '_public_read', v_table);
    execute format(
      'create policy %I on public.%I for select to anon, authenticated using (true)',
      'content_' || v_table || '_public_read', v_table);

    execute format('drop policy if exists %I on public.%I',
      'content_' || v_table || '_admin', v_table);
    execute format(
      'create policy %I on public.%I for all to authenticated
         using ((select public.current_user_admin()))
         with check ((select public.current_user_admin()))',
      'content_' || v_table || '_admin', v_table);
  end loop;
end $$;

-- ── Articles ──────────────────────────────────────────────────────────────────

alter table public.article enable row level security;

drop policy if exists "content_article_public_read" on public.article;
-- Inlined rather than calling content_article_public(id): the predicate is on this table's
-- own columns, so inlining lets the planner use the status and embargo indexes, and the
-- status lookup is an uncorrelated subselect evaluated once per statement. A correlated
-- function call per row would defeat both.
create policy "content_article_public_read" on public.article for select to anon, authenticated
  using (
    deleted_at is null
    and (embargo_until is null or embargo_until <= now())
    and article_status_id = (select id from public.article_status where slug = 'published')
  );

drop policy if exists "content_article_admin" on public.article;
create policy "content_article_admin" on public.article for all to authenticated
  using ((select public.current_user_admin()))
  with check ((select public.current_user_admin()));

-- ── Per-article content, visible exactly when its article is ──────────────────
--
-- Blocks, bylines and the join rows to taxonomy. Each is readable only through a publicly
-- visible article, so an unpublished draft leaks neither its body nor the fact that it is
-- filed under a particular topic.

do $$
declare
  v_table text;
begin
  foreach v_table in array array[
    'article_block', 'article_byline', 'article_section', 'article_topic', 'article_tag'
  ] loop
    execute format('alter table public.%I enable row level security', v_table);

    execute format('drop policy if exists %I on public.%I',
      'content_' || v_table || '_public_read', v_table);
    execute format(
      'create policy %I on public.%I for select to anon, authenticated
         using ((select public.content_article_public(article_id)))',
      'content_' || v_table || '_public_read', v_table);

    execute format('drop policy if exists %I on public.%I',
      'content_' || v_table || '_admin', v_table);
    execute format(
      'create policy %I on public.%I for all to authenticated
         using ((select public.current_user_admin()))
         with check ((select public.current_user_admin()))',
      'content_' || v_table || '_admin', v_table);
  end loop;
end $$;

-- ── Live coverage ─────────────────────────────────────────────────────────────
--
-- A live blog hangs off an article, and its updates off the coverage. Both follow the
-- article's visibility: coverage of an embargoed story must not be readable before the
-- story is.

alter table public.live_coverage enable row level security;

drop policy if exists "content_live_coverage_public_read" on public.live_coverage;
create policy "content_live_coverage_public_read" on public.live_coverage
  for select to anon, authenticated
  using ((select public.content_article_public(article_id)));

drop policy if exists "content_live_coverage_admin" on public.live_coverage;
create policy "content_live_coverage_admin" on public.live_coverage for all to authenticated
  using ((select public.current_user_admin()))
  with check ((select public.current_user_admin()));

alter table public.live_update enable row level security;

drop policy if exists "content_live_update_public_read" on public.live_update;
create policy "content_live_update_public_read" on public.live_update
  for select to anon, authenticated
  using (
    exists (
      select 1 from public.live_coverage c
      where c.id = live_coverage_id
        and (select public.content_article_public(c.article_id))
    )
  );

drop policy if exists "content_live_update_admin" on public.live_update;
create policy "content_live_update_admin" on public.live_update for all to authenticated
  using ((select public.current_user_admin()))
  with check ((select public.current_user_admin()));

-- ── Editorial workflow, licensing, and secrets: admin only ────────────────────
--
-- No public read of any kind. Revisions carry unpublished drafts; assignments and
-- checklists are internal process; media_asset_rights holds licensing terms that are
-- nobody else's business; and article_preview_token holds the credentials that let someone
-- read an unpublished article, so a public read would make every draft enumerable.
--
-- Note what is deliberately absent: no `for select using (true)`. These tables return
-- nothing to anon, which is why the preview route goes through the functions below rather
-- than reading the token table itself.

do $$
declare
  v_table text;
begin
  foreach v_table in array array[
    'article_revision', 'article_assignment', 'publish_checklist_item',
    'article_checklist_state', 'media_asset_rights', 'article_preview_token',
    'subscriber', 'newsletter_subscription'
  ] loop
    execute format('alter table public.%I enable row level security', v_table);

    execute format('drop policy if exists %I on public.%I',
      'content_' || v_table || '_admin', v_table);
    execute format(
      'create policy %I on public.%I for all to authenticated
         using ((select public.current_user_admin()))
         with check ((select public.current_user_admin()))',
      'content_' || v_table || '_admin', v_table);
  end loop;
end $$;

-- ── Comments ──────────────────────────────────────────────────────────────────

alter table public.comment enable row level security;

drop policy if exists "content_comment_public_read" on public.comment;
-- Approved comments on publicly visible articles. A pending or rejected comment is visible
-- to admins only, so moderation is not a thing readers watch happen.
create policy "content_comment_public_read" on public.comment for select to anon, authenticated
  using (status = 'approved' and (select public.content_article_public(article_id)));

drop policy if exists "content_comment_public_insert" on public.comment;
-- Anyone may submit a comment, on an article that is published and accepting them, and only
-- as pending: `with check` on the status column is what stops a submitter approving their
-- own comment by posting the field.
create policy "content_comment_public_insert" on public.comment for insert to anon, authenticated
  with check (
    status = 'pending'
    and (select public.content_article_public(article_id))
    and exists (select 1 from public.article a where a.id = article_id and a.allow_comment)
  );

drop policy if exists "content_comment_admin" on public.comment;
create policy "content_comment_admin" on public.comment for all to authenticated
  using ((select public.current_user_admin()))
  with check ((select public.current_user_admin()));

-- ── Newsletter signup ─────────────────────────────────────────────────────────
--
-- Signup needs to write `subscriber`, which anon cannot touch — deliberately, because it is
-- PII and a table anon could insert into is a table anon can probe: a unique-violation on
-- the email column answers "is this person subscribed?" for anyone who asks.
--
-- So signup goes through a definer function instead. It is idempotent, and it returns void
-- rather than an id or a status, so a caller learns nothing about whether the address was
-- already on the list.
create or replace function public.content_subscribe(
  p_email_address   text,
  p_newsletter_slug text,
  p_locale          text default 'en'
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_subscriber_id bigint;
  v_newsletter_id bigint;
begin
  if p_email_address is null or btrim(p_email_address) = '' then
    raise exception 'an email address is required';
  end if;

  select id into v_newsletter_id
  from public.newsletter
  where slug = p_newsletter_slug;

  if not found then
    raise exception 'no such newsletter';
  end if;

  insert into public.subscriber (email_address, locale)
  values (lower(btrim(p_email_address)), coalesce(nullif(btrim(p_locale), ''), 'en'))
  on conflict (email_address) do update set locale = excluded.locale
  returning id into v_subscriber_id;

  -- Re-subscribing clears a previous unsubscribe rather than inserting a second row.
  insert into public.newsletter_subscription (newsletter_id, subscriber_id)
  values (v_newsletter_id, v_subscriber_id)
  on conflict (newsletter_id, subscriber_id) do update set unsubscribed_at = null;
end;
$$;

grant execute on function public.content_subscribe(text, text, text) to anon, authenticated;

-- ── Moving an article through the workflow ────────────────────────────────────
--
-- Three statements: resolve the target status, enforce the publish gate, and update the
-- article — stamping published_at the first time it goes live, and only the first time, so a
-- republish does not rewrite the date the story broke.
--
-- The checklist gate lives here rather than only in the route because it is the one rule that
-- must not be bypassable: an editor posting the form directly, a script, or a future second
-- screen all go through this. The editorial checks that need resolved copy — a headline within
-- Google's length limit, a dek, a byline, alt text on every image — stay in
-- validateArticleForPublish, because SQL has no dictionary and the answer depends on which
-- locale is being published.
--
-- SECURITY INVOKER, so the update is still checked against the article admin policy.
create or replace function public.content_transition_article_status(
  p_article_id  bigint,
  p_status_slug text
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_status_id   bigint;
  v_unsatisfied text;
  v_updated     integer;
begin
  select id into v_status_id from public.article_status where slug = p_status_slug;
  if not found then
    raise exception 'no article_status with slug %', p_status_slug;
  end if;

  if p_status_slug = 'published' then
    -- An item with no state row is unsatisfied, which is why this is a left join from the
    -- required items rather than a filter over the state table: never having ticked a box is
    -- the common case, not a missing record.
    select string_agg(i.slug, ', ' order by i.ordinal) into v_unsatisfied
    from public.publish_checklist_item i
    left join public.article_checklist_state s
      on s.publish_checklist_item_id = i.id and s.article_id = p_article_id
    where i.required and coalesce(s.satisfied, false) = false;

    if v_unsatisfied is not null then
      raise exception 'publish checklist incomplete: %', v_unsatisfied;
    end if;
  end if;

  update public.article
  set article_status_id = v_status_id,
      published_at = case
        when p_status_slug = 'published' and published_at is null then now()
        else published_at
      end
  where id = p_article_id;

  get diagnostics v_updated = row_count;
  if v_updated = 0 then
    -- Zero rows is RLS refusing, not a missing article: a caller who cannot see it got a
    -- different error above.
    raise exception insufficient_privilege
      using message = 'not permitted to change this article''s status';
  end if;
end;
$$;

grant execute on function
  public.content_transition_article_status(bigint, text) to authenticated;

-- ── Preview by token ──────────────────────────────────────────────────────────
--
-- A preview link has to show an article RLS otherwise hides, to someone who may not be
-- signed in at all. The token is the credential, so these take it as their argument and
-- return nothing at all for one that is unknown or expired.
--
-- Written as two functions over `article` and `article_block` rather than a read policy
-- admitting "any article with a live token", because a policy cannot see which token the
-- request presented — it would make every draft with an outstanding link world-readable.

create or replace function public.content_preview_article(p_token text)
returns setof public.article
language sql
stable
security definer
set search_path = ''
as $$
  select a.*
  from public.article a
  join public.article_preview_token t on t.article_id = a.id
  where t.token = p_token
    and t.expires_at > now()
    and a.deleted_at is null
$$;

create or replace function public.content_preview_blocks(p_token text)
returns setof public.article_block
language sql
stable
security definer
set search_path = ''
as $$
  select b.*
  from public.article_block b
  join public.article_preview_token t on t.article_id = b.article_id
  where t.token = p_token
    and t.expires_at > now()
$$;

grant execute on function public.content_preview_article(text) to anon, authenticated;
grant execute on function public.content_preview_blocks(text) to anon, authenticated;


-- supplemental: 03-base-rls.sql
-- RLS policies for scaffold-level tables: user_account, navigation_item
--
-- Predicates go through the helpers in 00-auth-functions.sql, which resolve
-- Supabase Auth's auth.uid() to the bigint domain principal. No policy here
-- references auth.uid() or auth.jwt() directly.
--
-- Two conventions every policy below follows, both from Supabase's RLS guidance:
--
--   1. Helpers are called as (select public.current_user_id()), not bare. The
--      subselect lets the planner hoist the STABLE function into an InitPlan
--      evaluated once per statement instead of once per row.
--   2. Every policy names its role with `to`. Without it a policy is also
--      evaluated for anon, which can never satisfy these predicates anyway.
--
-- current_user_admin() replaces the inline
-- `exists (select 1 from public.user_account where id = ... and admin)` this file
-- used to repeat. That subquery was both slower (an RLS-checked read per policy
-- evaluation) and, on user_account itself, a self-reference inside a policy on the
-- same table — which Postgres rejects with "infinite recursion detected in policy
-- for relation". See 00-auth-functions.sql for why the helper is SECURITY DEFINER.

alter table public.user_account enable row level security;

drop policy if exists "user_account_owner_read" on public.user_account;
create policy "user_account_owner_read"
  on public.user_account for select
  to authenticated
  using ((select public.current_user_id()) = id);

drop policy if exists "user_account_owner_update" on public.user_account;
create policy "user_account_owner_update"
  on public.user_account for update
  to authenticated
  using ((select public.current_user_id()) = id)
  with check ((select public.current_user_id()) = id);

drop policy if exists "user_account_admin_all" on public.user_account;
create policy "user_account_admin_all"
  on public.user_account for all
  to authenticated
  using ((select public.current_user_admin()))
  with check ((select public.current_user_admin()));

-- No insert policy, deliberately. Rows are created only by
-- public.ensure_user_account() (SECURITY DEFINER), which derives the auth identity
-- from auth.uid() so a caller cannot provision a principal for someone else.
-- Adding a self-insert policy here would reopen that.

-- ────────────────────────────────────────────────────────────────────────────

alter table public.navigation_item enable row level security;

drop policy if exists "navigation_item_public_read" on public.navigation_item;
create policy "navigation_item_public_read"
  on public.navigation_item for select
  to anon, authenticated
  using (active);

drop policy if exists "navigation_item_admin_write" on public.navigation_item;
create policy "navigation_item_admin_write"
  on public.navigation_item for all
  to authenticated
  using ((select public.current_user_admin()))
  with check ((select public.current_user_admin()));


-- supplemental: 04-admin-write-rpc.sql
-- Compound admin writes
--
-- PostgREST has no client-side transactions: two supabase-js calls are two
-- transactions, so a failure between them leaves half-written state — an i18n link
-- with no copy, or copy with no link. These functions exist only where a mutation
-- spans more than one statement and a partial result would be garbage. Everything
-- expressible as a single statement stays in the route as a plain supabase-js call.
--
-- SECURITY INVOKER (the default, stated here because the contrast matters) is
-- load-bearing: the body runs as the calling role, so every statement inside is
-- still checked against the admin-write RLS policies on local_text_link,
-- local_text, and navigation_item. These functions buy atomicity, not privilege —
-- unlike the SECURITY DEFINER helpers in 00-auth-functions.sql, which deliberately
-- bypass RLS and are therefore written to take no caller-supplied identity.

-- ── local_text_link + local_text ──────────────────────────────────────────────

-- Dropped and recreated rather than `create or replace`d, because adding a parameter makes a
-- new signature: the four-argument version would survive alongside it and a four-argument call
-- would then be ambiguous between the two. Existing callers that pass four arguments still work
-- through p_entity_id's default.
drop function if exists public.create_local_text_entry(text, text, bigint[], text[]);

create or replace function public.create_local_text_entry(
  p_slug       text,
  p_scope      text,
  p_locale_ids bigint[],
  p_contents   text[],
  -- Entity-bound copy: an article's headline, a supplier's name. Null is global or scoped UI
  -- copy, which is what the local-text admin screen creates.
  p_entity_id  bigint default null
)
returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_link_id bigint;
begin
  if p_slug is null or btrim(p_slug) = '' then
    raise exception 'slug is required';
  end if;

  if coalesce(array_length(p_locale_ids, 1), 0)
     <> coalesce(array_length(p_contents, 1), 0) then
    raise exception 'locale_ids and contents must have the same length';
  end if;

  insert into public.local_text_link (slug, scope, entity_id)
  values (btrim(p_slug), nullif(btrim(coalesce(p_scope, '')), ''), p_entity_id)
  returning id into v_link_id;

  -- Blank translations are skipped rather than stored as empty copy.
  insert into public.local_text (link, locale, content)
  select v_link_id, p_locale_ids[i], btrim(p_contents[i])
  from generate_subscripts(p_contents, 1) as i
  where btrim(coalesce(p_contents[i], '')) <> '';

  return v_link_id;
end;
$$;

create or replace function public.delete_local_text_entry(p_link_id bigint)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  -- local_text.link is ON DELETE RESTRICT, so the copy rows have to go first.
  delete from public.local_text where link = p_link_id;
  delete from public.local_text_link where id = p_link_id;
end;
$$;

-- ── navigation_item + its copy link ───────────────────────────────────────────

create or replace function public.create_navigation_item(
  p_slug       text,
  p_href       text,
  p_scope      text,
  p_sort_order integer default 0
)
returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_link_id bigint;
  v_id      bigint;
begin
  if p_slug is null or btrim(p_slug) = ''
     or p_href is null or btrim(p_href) = ''
     or p_scope is null or btrim(p_scope) = '' then
    raise exception 'slug, href, and scope are required';
  end if;

  insert into public.local_text_link (slug, scope, entity_id)
  values (btrim(p_slug), null, null)
  returning id into v_link_id;

  insert into public.navigation_item (local_text_link_id, href, scope, sort_order)
  values (v_link_id, btrim(p_href), btrim(p_scope), coalesce(p_sort_order, 0))
  returning id into v_id;

  return v_id;
end;
$$;

create or replace function public.delete_navigation_item(p_id bigint)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_link_id bigint;
begin
  select ni.local_text_link_id into v_link_id
  from public.navigation_item ni
  where ni.id = p_id;

  delete from public.navigation_item where id = p_id;

  if v_link_id is not null then
    delete from public.local_text where link = v_link_id;
    delete from public.local_text_link where id = v_link_id;
  end if;
end;
$$;

-- ── Grants ────────────────────────────────────────────────────────────────────
--
-- These all write, so anon gets nothing. RLS still decides whether the caller is
-- actually allowed to touch the rows.

grant execute on function
  public.create_local_text_entry(text, text, bigint[], text[], bigint) to authenticated;
grant execute on function public.delete_local_text_entry(bigint) to authenticated;
grant execute on function
  public.create_navigation_item(text, text, text, integer) to authenticated;
grant execute on function public.delete_navigation_item(bigint) to authenticated;

-- supplemental: 05-newsroom-admin-rpc.sql
-- Newsroom admin compound writes
--
-- Same rationale as 04-admin-write-rpc.sql, applied to the article editor: PostgREST
-- has no client-side transactions, so anything spanning more than one statement whose
-- partial result would be garbage belongs in a function. Editing an article's copy is
-- the textbook case — a local_text_link with no local_text row renders as a
-- `[missing: …]` sentinel on the public page, which is worse than the edit failing.
--
-- SECURITY INVOKER throughout, stated explicitly because it is load-bearing: the body
-- runs as the caller, so the content module's admin-write policies still check every
-- statement inside. These buy atomicity, not privilege. Anything expressible as one
-- statement stays a plain supabase-js call in the route.
--
-- set search_path = '' with every reference schema-qualified, per CLAUDE.md.

-- ── Entity-bound copy ─────────────────────────────────────────────────────────

-- Upserts one locale's text for one (slug, scope, entity_id) key, creating the link if
-- it does not exist yet. create_local_text_entry only ever inserts a link, so it cannot
-- serve an editor re-saving a headline that already has one.
--
-- Blank content deletes that locale's row rather than storing an empty string, so a
-- cleared field falls back to the default locale instead of rendering as blank. The link
-- is left in place: it is the identity of the field, not of the translation.
create or replace function public.set_entity_copy(
  p_slug      text,
  p_scope     text,
  p_entity_id bigint,
  p_locale_id bigint,
  p_content   text
)
returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_link_id bigint;
begin
  if p_slug is null or btrim(p_slug) = '' then
    raise exception 'slug is required';
  end if;
  if p_locale_id is null then
    raise exception 'locale_id is required';
  end if;

  -- Inference on the three columns rather than a named constraint, matching the
  -- seed convention. The index is NULLS NOT DISTINCT, so a global key (both null)
  -- conflicts correctly instead of inserting a duplicate.
  insert into public.local_text_link (slug, scope, entity_id)
  values (btrim(p_slug), nullif(btrim(coalesce(p_scope, '')), ''), p_entity_id)
  on conflict (slug, scope, entity_id) do update
    set slug = excluded.slug
  returning id into v_link_id;

  if btrim(coalesce(p_content, '')) = '' then
    delete from public.local_text where link = v_link_id and locale = p_locale_id;
  else
    insert into public.local_text (link, locale, content)
    values (v_link_id, p_locale_id, btrim(p_content))
    on conflict (link, locale) do update set content = excluded.content;
  end if;

  return v_link_id;
end;
$$;

-- ── Article body blocks ───────────────────────────────────────────────────────

-- Creates or updates one block and its prose together. p_block_id null inserts.
--
-- Position is not unique on article_block, so a new block takes max(position) + 1
-- rather than relying on a conflict target that does not exist.
create or replace function public.upsert_article_block(
  p_article_id     bigint,
  p_block_type     text,
  p_text           text,
  p_locale_id      bigint,
  p_block_id       bigint default null,
  p_content        jsonb default '{}'::jsonb,
  p_media_asset_id bigint default null
)
returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_block_id bigint;
begin
  if p_article_id is null then
    raise exception 'article_id is required';
  end if;

  if p_block_id is null then
    insert into public.article_block (article_id, block_type, position, content, media_asset_id)
    values (
      p_article_id,
      p_block_type::public.article_block_type,
      coalesce(
        (select max(b.position) from public.article_block b where b.article_id = p_article_id),
        0
      ) + 1,
      coalesce(p_content, '{}'::jsonb),
      p_media_asset_id
    )
    returning id into v_block_id;
  else
    update public.article_block
    set block_type = p_block_type::public.article_block_type,
        content = coalesce(p_content, '{}'::jsonb),
        media_asset_id = p_media_asset_id
    where id = p_block_id and article_id = p_article_id
    returning id into v_block_id;

    -- Null means the update matched nothing, which under RLS is indistinguishable
    -- from "not allowed" — either way the caller asked for a block it cannot write.
    if v_block_id is null then
      raise exception 'block % not found on article %', p_block_id, p_article_id;
    end if;
  end if;

  perform public.set_entity_copy('text', 'article_block', v_block_id, p_locale_id, p_text);

  return v_block_id;
end;
$$;

-- Removes a block and the copy keyed to it. local_text_link.entity_id is polymorphic
-- and carries no foreign key by design, so nothing cascades — the copy has to be
-- deleted here or it is orphaned, and a later block reusing that id would inherit it.
create or replace function public.delete_article_block(p_block_id bigint)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_link_id bigint;
begin
  select l.id into v_link_id
  from public.local_text_link l
  where l.scope = 'article_block' and l.slug = 'text' and l.entity_id = p_block_id;

  if v_link_id is not null then
    delete from public.local_text where link = v_link_id;
    delete from public.local_text_link where id = v_link_id;
  end if;

  delete from public.article_block where id = p_block_id;
end;
$$;

-- Writes a whole ordering in one statement set. Reordering by individual updates would
-- leave the body scrambled if the second call failed.
create or replace function public.reorder_article_blocks(
  p_article_id bigint,
  p_block_ids  bigint[]
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  update public.article_block b
  set position = v.ordinal
  from (
    select id, ordinal
    from unnest(p_block_ids) with ordinality as t(id, ordinal)
  ) as v
  where b.id = v.id and b.article_id = p_article_id;
end;
$$;

-- ── Bylines and filing ────────────────────────────────────────────────────────

-- Replaces the byline list, in order. Delete-then-insert is two statements, and a
-- failure between them would leave an article with no byline at all.
create or replace function public.set_article_bylines(
  p_article_id bigint,
  p_author_ids bigint[]
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  delete from public.article_byline
  where article_id = p_article_id
    and (p_author_ids is null or author_profile_id <> all (p_author_ids));

  insert into public.article_byline (article_id, author_profile_id, position)
  select p_article_id, v.id, v.ordinal
  from unnest(coalesce(p_author_ids, '{}'::bigint[])) with ordinality as v(id, ordinal)
  on conflict (article_id, author_profile_id) do update set position = excluded.position;
end;
$$;

-- Replaces all three filing dimensions together. They are edited as one form, and a
-- partial apply would file a story under its new sections but its old topics.
create or replace function public.set_article_filing(
  p_article_id  bigint,
  p_section_ids bigint[],
  p_topic_ids   bigint[],
  p_tag_ids     bigint[]
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  delete from public.article_section
  where article_id = p_article_id
    and (p_section_ids is null or section_id <> all (p_section_ids));
  insert into public.article_section (article_id, section_id)
  select p_article_id, id from unnest(coalesce(p_section_ids, '{}'::bigint[])) as id
  on conflict (article_id, section_id) do nothing;

  delete from public.article_topic
  where article_id = p_article_id
    and (p_topic_ids is null or topic_id <> all (p_topic_ids));
  insert into public.article_topic (article_id, topic_id)
  select p_article_id, id from unnest(coalesce(p_topic_ids, '{}'::bigint[])) as id
  on conflict (article_id, topic_id) do nothing;

  delete from public.article_tag
  where article_id = p_article_id
    and (p_tag_ids is null or tag_id <> all (p_tag_ids));
  insert into public.article_tag (article_id, tag_id)
  select p_article_id, id from unnest(coalesce(p_tag_ids, '{}'::bigint[])) as id
  on conflict (article_id, tag_id) do nothing;
end;
$$;

-- ── Grants ────────────────────────────────────────────────────────────────────
-- authenticated, not anon. These are SECURITY INVOKER, so RLS is what actually
-- decides whether a given principal's statements are allowed; the grant only
-- controls who may attempt the call.
grant execute on function
  public.set_entity_copy(text, text, bigint, bigint, text) to authenticated;
grant execute on function
  public.upsert_article_block(bigint, text, text, bigint, bigint, jsonb, bigint) to authenticated;
grant execute on function public.delete_article_block(bigint) to authenticated;
grant execute on function public.reorder_article_blocks(bigint, bigint[]) to authenticated;
grant execute on function public.set_article_bylines(bigint, bigint[]) to authenticated;
grant execute on function
  public.set_article_filing(bigint, bigint[], bigint[], bigint[]) to authenticated;

-- ── People ────────────────────────────────────────────────────────────────────

-- Lists principals with the email of the auth identity behind each.
--
-- SECURITY DEFINER, which is the opposite of everything above, and for a specific
-- reason: `auth.users` is not in PostgREST's exposed schemas, so no amount of RLS on
-- public tables makes an email readable through the Data API. A definer function is
-- the only way to join it, and the architecture deliberately keeps email out of
-- public.user_account rather than duplicating identity data.
--
-- Because it is definer, RLS does not apply inside, so the admin check is explicit and
-- comes first. Without it any authenticated caller could enumerate every email in the
-- system. It takes no caller-supplied identity for the same reason the auth helpers
-- do not: there is nothing to pass that could be forged.
create or replace function public.admin_list_people()
returns table (
  user_account_id bigint,
  email           text,
  admin           boolean,
  created_at      timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not coalesce((select public.current_user_admin()), false) then
    raise exception 'admin privileges required';
  end if;

  return query
  select ua.id, au.email::text, ua.admin, ua.created_at
  from public.user_account ua
  left join auth.users au on au.id = ua.auth_user_id
  order by ua.id;
end;
$$;

-- Counts the admins, so the UI can refuse to remove the last one. Definer for the
-- same reason: a non-admin must not be able to probe the shape of the admin set, and
-- an admin's own RLS view of user_account is not guaranteed to cover every row.
create or replace function public.admin_count()
returns integer
language sql
security definer
stable
set search_path = ''
as $$
  select count(*)::integer from public.user_account where admin;
$$;

grant execute on function public.admin_list_people() to authenticated;
grant execute on function public.admin_count() to authenticated;


-- supplemental: 06-user-account-hardening.sql
-- user_account: close the self-promotion hole
--
-- CONFIRMED EXPLOITABLE before this file existed. As any authenticated principal:
--
--   PATCH /rest/v1/user_account?id=eq.<own id>   {"admin": true}
--
-- returned 200 with the row updated, after which public.current_user_admin() returned
-- true and that principal held the whole (admin) area. Verified end to end, not
-- theorised.
--
-- Two things combined to allow it. Supabase's bootstrap grants give anon and
-- authenticated full DML on everything in `public` — the same root cause as the
-- content module's RLS incident — so RLS is the only restraint. And the base
-- template's `user_account_owner_update` policy permits a principal to update its own
-- row: `using (current_user_id() = id) with check (current_user_id() = id)`. Postgres
-- RLS cannot restrict which *columns* an allowed UPDATE may touch, so "update your own
-- row" necessarily includes `admin`. It also includes `auth_user_id`, which is an
-- account-takeover primitive: repoint your principal at someone else's identity.
--
-- The fix is column privileges rather than a policy, because that is the only
-- mechanism in Postgres that operates at column granularity. A principal has no
-- legitimate reason to write any column of its own row — id, auth_user_id,
-- created_at, updated_at, active and admin are all either identity or administration
-- — so write access goes away entirely and the one legitimate change, promoting or
-- demoting an administrator, moves to a definer function that checks caller admin
-- status itself.
--
-- SELECT is deliberately left in place: `user_account_owner_read` is what lets the
-- (admin) layout read its own `admin` flag, and `user_account_admin_all` is what lets
-- an administrator read the roster.

revoke insert, update, delete, truncate, references, trigger
  on public.user_account from anon, authenticated;

-- Permits nothing once UPDATE is revoked, and leaving it in place would imply a
-- self-service surface that does not exist.
drop policy if exists user_account_owner_update on public.user_account;

-- The only sanctioned write. SECURITY DEFINER because the caller has no UPDATE
-- privilege at all now, so the admin check and the last-administrator guard both have
-- to live in here — a guard enforced only in the route could be skipped by calling
-- the Data API directly, which is exactly how the hole above was proven.
create or replace function public.admin_set_user_admin(
  p_user_account_id bigint,
  p_admin           boolean
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_admin_count integer;
begin
  if not coalesce((select public.current_user_admin()), false) then
    raise exception 'admin privileges required';
  end if;

  if p_user_account_id is null or p_admin is null then
    raise exception 'user_account_id and admin are both required';
  end if;

  -- Removing the last administrator would lock everyone out of the admin area with no
  -- route back in but direct SQL. Counted here rather than in the route so the guard
  -- holds for any caller.
  if p_admin = false then
    select count(*) into v_admin_count from public.user_account where admin;
    if v_admin_count <= 1 then
      raise exception 'there has to be at least one administrator';
    end if;
  end if;

  update public.user_account
  set admin = p_admin,
      updated_at = now()
  where id = p_user_account_id;

  if not found then
    raise exception 'no such principal';
  end if;
end;
$$;

grant execute on function public.admin_set_user_admin(bigint, boolean) to authenticated;
